version: '3.9'

services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - default

  nestapp:
    container_name: users
    image: users:1.0.0
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_USERNAME=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=test
      - PG_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}